/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows;

/**
 *
 * @author Antonio Rodriguez
 */
public class CrearGrupo extends javax.swing.JFrame {

    /**
     * Creates new form CrearGrupo
     */
    public CrearGrupo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombregrupo = new javax.swing.JTextField();
        txtJugadores = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdJug = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear grupo");
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(64, 34, 0, 0);

        jLabel4.setFont(new java.awt.Font("Minecrafter", 0, 24)); // NOI18N
        jLabel4.setText("Nombre del  grupo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(330, 250, 300, 32);

        jLabel5.setFont(new java.awt.Font("Minecrafter", 0, 24)); // NOI18N
        jLabel5.setText("cantidad de jugadores");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(330, 310, 333, 24);

        txtNombregrupo.setFont(new java.awt.Font("Minecrafter", 0, 24)); // NOI18N
        getContentPane().add(txtNombregrupo);
        txtNombregrupo.setBounds(710, 232, 290, 40);

        txtJugadores.setFont(new java.awt.Font("Minecrafter", 0, 24)); // NOI18N
        getContentPane().add(txtJugadores);
        txtJugadores.setBounds(710, 292, 290, 40);

        jLabel2.setFont(new java.awt.Font("Minecrafter", 0, 24)); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(42, 283, 222, 56);

        jLabel6.setFont(new java.awt.Font("Minecrafter", 0, 24)); // NOI18N
        jLabel6.setText("cedula de jugador");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(330, 360, 274, 40);

        txtIdJug.setFont(new java.awt.Font("Minecrafter", 0, 24)); // NOI18N
        getContentPane().add(txtIdJug);
        txtIdJug.setBounds(710, 352, 290, 40);

        jButton1.setFont(new java.awt.Font("Minecrafter", 0, 24)); // NOI18N
        jButton1.setText("Agregar");
        getContentPane().add(jButton1);
        jButton1.setBounds(780, 410, 150, 33);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Documents\\POO proyecto\\POO-Sokoban\\POO Sokoban\\src\\Images\\crear grupo.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 1280, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearGrupo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtIdJug;
    private javax.swing.JTextField txtJugadores;
    private javax.swing.JTextField txtNombregrupo;
    // End of variables declaration//GEN-END:variables
}
