/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows;

/**
 *
 * @author Antonio Rodriguez
 */
public class CrearGrupo extends javax.swing.JFrame {

    /**
     * Creates new form CrearGrupo
     */
    public CrearGrupo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombregrupo = new javax.swing.JTextField();
        txtjugadores = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNivel1 = new javax.swing.JTextField();
        txtNivel2 = new javax.swing.JTextField();
        txtNivel4 = new javax.swing.JTextField();
        txtNivel3 = new javax.swing.JTextField();
        txtNivel5 = new javax.swing.JTextField();
        botonAgregar_grupo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear grupo");
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(64, 34, 0, 0);

        jLabel4.setFont(new java.awt.Font("Minecrafter", 0, 24)); // NOI18N
        jLabel4.setText("Nombre del  Grupo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(390, 160, 276, 24);

        jLabel5.setFont(new java.awt.Font("Minecrafter", 0, 24)); // NOI18N
        jLabel5.setText("Cantidad de jugadores");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(390, 230, 333, 24);

        txtNombregrupo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        getContentPane().add(txtNombregrupo);
        txtNombregrupo.setBounds(740, 150, 169, 32);

        txtjugadores.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        getContentPane().add(txtjugadores);
        txtjugadores.setBounds(740, 230, 169, 32);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(42, 286, 222, 56);

        jLabel1.setFont(new java.awt.Font("Minecrafter", 0, 24)); // NOI18N
        jLabel1.setText("Niveles a jugar (Maximo 5)");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 290, 292, 32);

        txtNivel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        getContentPane().add(txtNivel1);
        txtNivel1.setBounds(740, 290, 169, 32);

        txtNivel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        getContentPane().add(txtNivel2);
        txtNivel2.setBounds(740, 350, 169, 32);

        txtNivel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        getContentPane().add(txtNivel4);
        txtNivel4.setBounds(740, 470, 169, 32);

        txtNivel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        getContentPane().add(txtNivel3);
        txtNivel3.setBounds(740, 410, 169, 32);

        txtNivel5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        getContentPane().add(txtNivel5);
        txtNivel5.setBounds(740, 530, 169, 32);

        botonAgregar_grupo.setFont(new java.awt.Font("Minecrafter", 0, 24)); // NOI18N
        botonAgregar_grupo.setText("Crear grupo");
        getContentPane().add(botonAgregar_grupo);
        botonAgregar_grupo.setBounds(410, 360, 212, 34);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/grupos.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 1250, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearGrupo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar_grupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtNivel1;
    private javax.swing.JTextField txtNivel2;
    private javax.swing.JTextField txtNivel3;
    private javax.swing.JTextField txtNivel4;
    private javax.swing.JTextField txtNivel5;
    private javax.swing.JTextField txtNombregrupo;
    private javax.swing.JTextField txtjugadores;
    // End of variables declaration//GEN-END:variables
}
