/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows;

/**
 *
 * @author Antonio Rodriguez
 */
public class Reportes5mejoresentodo extends javax.swing.JFrame {

    /**
     * Creates new form Reportes5mejoresentodo
     */
    public Reportes5mejoresentodo() {
        initComponents();
        panel5m.setVisible(false);
        panelM.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cmbCateg = new javax.swing.JComboBox<>();
        txtNivel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        panel5m = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        txtQuinto = new javax.swing.JTextField();
        txtPrimer = new javax.swing.JTextField();
        txtSegundo = new javax.swing.JTextField();
        txtCuarto = new javax.swing.JTextField();
        txtTercero = new javax.swing.JTextField();
        txtQuintoC = new javax.swing.JTextField();
        txtPrimerC = new javax.swing.JTextField();
        txtSegundoC = new javax.swing.JTextField();
        txtTerceroC = new javax.swing.JTextField();
        txtCuartoC = new javax.swing.JTextField();
        panelM = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Minecraft z2font", 0, 18)); // NOI18N
        jLabel2.setText("Selecione la categoria en la que desea ver estadisticas");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 140, 870, 40);

        cmbCateg.setBackground(new java.awt.Color(240, 240, 240));
        cmbCateg.setFont(new java.awt.Font("Minecrafter", 0, 24)); // NOI18N
        cmbCateg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 Usuarios más insistentes en nivel", "5 Usuarios con ganes optimizados", "5 Usuarios records rotos", "Mejor en movimientos", "Mejor en tiempo", "Usuarios que pasaron un nivel", "Historial de un jugador", "Informacion de nivel creado por administrador" }));
        cmbCateg.setSelectedIndex(-1);
        cmbCateg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCateg);
        cmbCateg.setBounds(300, 190, 720, 40);

        txtNivel.setBackground(new java.awt.Color(120, 213, 233));
        txtNivel.setFont(new java.awt.Font("Minecrafter", 0, 24)); // NOI18N
        txtNivel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNivelActionPerformed(evt);
            }
        });
        getContentPane().add(txtNivel);
        txtNivel.setBounds(590, 240, 210, 40);

        jLabel1.setFont(new java.awt.Font("Minecraft z2font", 0, 18)); // NOI18N
        jLabel1.setText("Nivel");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(422, 240, 100, 18);

        panel5m.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Minecraft z2font", 0, 18)); // NOI18N
        jLabel4.setText("Cantidad");
        panel5m.add(jLabel4);
        jLabel4.setBounds(350, 0, 190, 60);

        jLabel8.setFont(new java.awt.Font("Minecraft z2font", 0, 18)); // NOI18N
        jLabel8.setText("Nombre");
        panel5m.add(jLabel8);
        jLabel8.setBounds(50, 10, 190, 30);

        jTextField2.setBackground(new java.awt.Color(120, 213, 233));
        jTextField2.setFont(new java.awt.Font("Minecrafter", 0, 24)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        panel5m.add(jTextField2);
        jTextField2.setBounds(590, 240, 210, 40);

        txtQuinto.setFont(new java.awt.Font("Minecrafter", 0, 14)); // NOI18N
        txtQuinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuintoActionPerformed(evt);
            }
        });
        panel5m.add(txtQuinto);
        txtQuinto.setBounds(10, 220, 260, 26);

        txtPrimer.setFont(new java.awt.Font("Minecrafter", 0, 14)); // NOI18N
        txtPrimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimerActionPerformed(evt);
            }
        });
        panel5m.add(txtPrimer);
        txtPrimer.setBounds(10, 60, 260, 26);

        txtSegundo.setFont(new java.awt.Font("Minecrafter", 0, 14)); // NOI18N
        panel5m.add(txtSegundo);
        txtSegundo.setBounds(10, 100, 260, 26);

        txtCuarto.setFont(new java.awt.Font("Minecrafter", 0, 14)); // NOI18N
        panel5m.add(txtCuarto);
        txtCuarto.setBounds(10, 180, 260, 26);

        txtTercero.setFont(new java.awt.Font("Minecrafter", 0, 14)); // NOI18N
        txtTercero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTerceroActionPerformed(evt);
            }
        });
        panel5m.add(txtTercero);
        txtTercero.setBounds(10, 140, 260, 26);

        txtQuintoC.setFont(new java.awt.Font("Minecrafter", 0, 14)); // NOI18N
        txtQuintoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuintoCActionPerformed(evt);
            }
        });
        panel5m.add(txtQuintoC);
        txtQuintoC.setBounds(290, 220, 260, 26);

        txtPrimerC.setFont(new java.awt.Font("Minecrafter", 0, 14)); // NOI18N
        txtPrimerC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimerCActionPerformed(evt);
            }
        });
        panel5m.add(txtPrimerC);
        txtPrimerC.setBounds(290, 60, 260, 26);

        txtSegundoC.setFont(new java.awt.Font("Minecrafter", 0, 14)); // NOI18N
        panel5m.add(txtSegundoC);
        txtSegundoC.setBounds(290, 100, 260, 26);

        txtTerceroC.setFont(new java.awt.Font("Minecrafter", 0, 14)); // NOI18N
        txtTerceroC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTerceroCActionPerformed(evt);
            }
        });
        panel5m.add(txtTerceroC);
        txtTerceroC.setBounds(290, 140, 260, 26);

        txtCuartoC.setFont(new java.awt.Font("Minecrafter", 0, 14)); // NOI18N
        panel5m.add(txtCuartoC);
        txtCuartoC.setBounds(290, 180, 260, 26);

        panelM.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Minecrafter", 0, 18)); // NOI18N
        jLabel9.setText("Nombre");
        panelM.add(jLabel9);
        jLabel9.setBounds(10, 10, 190, 30);

        txtNombre.setFont(new java.awt.Font("Minecrafter", 0, 14)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        panelM.add(txtNombre);
        txtNombre.setBounds(150, 10, 260, 30);

        panel5m.add(panelM);
        panelM.setBounds(0, 50, 690, 160);

        getContentPane().add(panel5m);
        panel5m.setBounds(380, 290, 580, 270);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/estadisticas.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNivelActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void txtPrimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimerActionPerformed

    private void txtTerceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTerceroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTerceroActionPerformed

    private void txtQuintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuintoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuintoActionPerformed

    private void cmbCategActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategActionPerformed
        if (cmbCateg.getSelectedIndex()==0 | cmbCateg.getSelectedIndex()==1 | cmbCateg.getSelectedIndex()==2)
            panel5m.setVisible(true);
        else if (cmbCateg.getSelectedIndex()==3 | cmbCateg.getSelectedIndex()==4)
            panelM.setVisible(true);
    }//GEN-LAST:event_cmbCategActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtQuintoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuintoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuintoCActionPerformed

    private void txtPrimerCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimerCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimerCActionPerformed

    private void txtTerceroCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTerceroCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTerceroCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Reportes5mejoresentodo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCateg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel panel5m;
    private javax.swing.JPanel panelM;
    private javax.swing.JTextField txtCuarto;
    private javax.swing.JTextField txtCuartoC;
    private javax.swing.JTextField txtNivel;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrimer;
    private javax.swing.JTextField txtPrimerC;
    private javax.swing.JTextField txtQuinto;
    private javax.swing.JTextField txtQuintoC;
    private javax.swing.JTextField txtSegundo;
    private javax.swing.JTextField txtSegundoC;
    private javax.swing.JTextField txtTercero;
    private javax.swing.JTextField txtTerceroC;
    // End of variables declaration//GEN-END:variables
}
