/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows;

import Class.SokobanPrincipal;
import Class.Nivel;
import java.util.Iterator;


/**
 *
 * @author Peniche
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Reportes
     */
    public Reportes() {
        initComponents();
      
        setResizable(false);    // no poder cambiar tamano a la ventana
        setSize(900,620);      // tamano
        setLocationRelativeTo(null);    // posicionar ventana en centro
        setTitle("Reportes");   // poner titulo a ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbReportes = new javax.swing.JComboBox<>();
        botonMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaReportes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        cmbReportes.setFont(new java.awt.Font("Minecrafter", 0, 14)); // NOI18N
        cmbReportes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. Niveles con la informacion por nivel que ha introducido un administrador.", "2. Historial de juego con toda la información de un usuario normal X.", "3. Imprimir los 5 usuarios con más ganes óptimos.", "4. Imprimir los 5 usuarios con más records rotos.", "5. Imprimir los 5 usuarios más insistentes en un nivel x.", "6. Imprimir todos los usuarios que han superado un nivel X.", "7. Imprimir las estadísticas de un usuario X.", " " }));
        getContentPane().add(cmbReportes);
        cmbReportes.setBounds(70, 120, 730, 30);

        botonMostrar.setFont(new java.awt.Font("Minecrafter", 0, 24)); // NOI18N
        botonMostrar.setText("Mostrar");
        botonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(botonMostrar);
        botonMostrar.setBounds(370, 454, 160, 40);

        AreaReportes.setColumns(20);
        AreaReportes.setRows(5);
        jScrollPane1.setViewportView(AreaReportes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 200, 580, 220);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void botonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarActionPerformed
            
            if(cmbReportes.getSelectedIndex()==0){
               if(!SokobanPrincipal.listaNiveles.isEmpty()) { 
                    Iterator iterador = SokobanPrincipal.listaNiveles.listIterator(); 
                    while(iterador.hasNext()) {
                        AreaReportes.append(iterador.next() + "\n");
                    }
                }
               else{
                   AreaReportes.setText("Lista Vacia");
               }
                 
            }
    }//GEN-LAST:event_botonMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaReportes;
    private javax.swing.JButton botonMostrar;
    private javax.swing.JComboBox<String> cmbReportes;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
